[project]
name = "os2autoprocess"
dynamic = ["version"]
description = 'Modul til at opdatere fase/status på en process i os2autoprocess'
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { name = "Nicki Kielsen", email = "Nicki.kielsen@brk.dk" },
]

[tool.ruff]
target-version = "py37"
line-length = 140